spring.application.name=forgetask

spring.config.import=optional:file:.env[.properties]

# --- UCP / Oracle ATP ---
spring.datasource.url=jdbc:oracle:thin:@ocichatbot_tp?TNS_ADMIN=${TNS_ADMIN:./wallet}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource

spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.user=${spring.datasource.username}
spring.datasource.oracleucp.password=${spring.datasource.password}
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=${spring.application.name}-${random.uuid}
spring.datasource.oracleucp.initial-pool-size=5
spring.datasource.oracleucp.min-pool-size=5
spring.datasource.oracleucp.max-pool-size=20

oracle.net.tns_admin=${TNS_ADMIN:./wallet}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT ---
jwt.secret=${JWT_SECRET:mDaVxD%N2KT#g*X#N3AX1Bt%Av$UnfXAv0%k3S0he4T9utES*Pnr1GR!$*dey3H0}
jwt.expiration-ms=86400000


# --- Telegram Bot Configuration ---
telegram.bot.enabled=${TELEGRAM_BOT_ENABLED:false}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.name=${TELEGRAM_BOT_NAME:}

server.address=0.0.0.0

