apiVersion: v1
kind: Service
metadata:
  name: forgetask-frontend-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: forgetask-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgetask-frontend-deployment
spec:
  selector:
    matchLabels:
      app: forgetask-frontend
  replicas: 1 # Ajustar en otro sprint 2 o 3 para alta disponibilidad
  template:
    metadata:
      labels:
        app: forgetask-frontend
        version: v1
    spec:
      containers:
        - name: forgetask-frontend
          image: "%DOCKER_REGISTRY%/forgetask-frontend:%IMAGE_VERSION%"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_USE_PROXY
              value: "true"
            - name: BACKEND_INTERNAL_URL
              value: "http://forgetask-service.mtdrworkshop.svc.cluster.local:8080"
      restartPolicy: Always
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: forgetask-frontend